### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by till** [GuillaumeSmaha/ansible-role-gluu-setup#3]
Hey,

been trying your roles for Gluu — kudos for open sourcing it and sharing your work.

I had one question about the dependencies. I am assuming these are Gluu dependencies? Or dependencies of your playbook? I installed them locally, but I am guessing they need to be installed on the machine I am deploying Gluu too?

If the latter is the case, should I send a PR to include them in the role?

Till

**Comment by GuillaumeSmaha** [comment]
Hi,

The dependency for the playbook is only `dnspython>=1.15.0`.
dnspython is used by the deployer machine to find the IP address from the DNS name.

On the target machine, you need to install python to run ansible on it.
See https://docs.ansible.com/ansible/2.7/installation_guide/intro_installation.html#managed-node-requirements for Ansible requirements.
Gluu is packaged in a `deb` or `rpm` file by Gluu Team, so all dependencies are managed by their package.
Also Gluu is installed in a systemd container in `/opt/gluu-server-xxx`, so the environment is totally controlled by Gluu.
That why, you have on the target machine, the command `service gluu login` or a ssh service on port `60022` to enter in the container.

Does that answer your questions?
If you want I can explain more what is done by the role.

Guillaume

**Comment by till** [comment]
@GuillaumeSmaha This is very helpful. Thanks for responding.

## Deps

I'll update my setup to only require `dnspython` locally then.

If you check this out though, it suggests I need to install all the dependencies: https://github.com/GuillaumeSmaha/ansible-role-gluu-configuration#requirements — Maybe that can be reworded? I am happy to send PRs. But I wanted to make sure I didn't misunderstand.

## For the installation

I did notice it's trying to start Gluu using `systemd-nspawn` (a SystemD chroot/container) which I was unaware of its existence 😆 until I hit some odd start-up error (which I think is related to my environment, trying to confirm that before I report with more details).

On that note, is the SystemD container your choice? I had not seen that when I setup Gluu manually (using their documentation). Also, from glancing over some docs, it seems like running SSH in it isn't necessary, or is that for Ansible to do its magic?

---

Thanks again for taking the time to respond. 👍

**Comment by GuillaumeSmaha** [comment]
# Deps
Oh yes, I forgot I have different requirements for each role. Sorry :D
I think Ansible run filter plugins on the target node, so pyDes is maybe not necessary on the deployer machine. In the gluu role setup, I install the same deps on the target machine:
https://github.com/GuillaumeSmaha/ansible-role-gluu-setup/blob/master/tasks/main.yml#L17
To be simplier, I chose to install the same deps on the deployer and target machine.
But I should check for each deps if it is required or not on the deployer and on the target machine.

# For the installation
I use the Gluu apt/yum repository they provided: https://repo.gluu.org/ like they explains in https://gluu.org/docs/ce/installation-guide/install/.
I didn't choose to run it in a systemd chroot/container, this is provided by the package installation.

You are right the SSH service is not run anymore in the container. It was true in a previous version of Gluu. Now, I run commands in the container with `/usr/sbin/chroot /opt/gluu-server-xxx/ sh -c "command"`


I am going to explain what is done by the roles over the default gluu setup, so you can better understand my approach.
I worked on custom scripts and often when I made a mistake, I blocked totally my Gluu server. So I wanted to install quickly a new gluu server from scratch.
After searching a lot on Guu to understand how it works. I found that all important data are stored in the LDAP, even the custom scripts.
So I created a first ansible role https://github.com/GuillaumeSmaha/ansible-role-gluu to install and configure Gluu.
After, the need evolves and the script was used to install and configure the production servers. So, I split the basic installation from the configuration, and I created the different roles.
The role `gluu-setup` mainly do:
- Install gluu repository
- Install gluu package which installs the chroot container.
- Create a custom `setup.properties` file.
This is the big part of my ansible role. Because all is done here: the services (ldap, oxauth, oxtrust, ...) to install, the default password, ...
- It call the script to setup gluu in the chroot. This script read the file `setup.properties`
You can find the script provided by gluu here: https://github.com/GluuFederation/community-edition-setup. This script is also installed by the gluu package.
- After that, this is mainly a management for the certificates and ldap replication and also to update the config to connect on a remote LDAP (if you have a cluster). 
Now, gluu-setup is not necessary anymore unless you update the architecture of the machine.


The role `gluu-configuration` updates the configuration inside LDAP with a easier way for each part (scripts, attributes, ...).
This role doesn't install/update/delete any file on the target machine. It just need a target machine because the configuration and the LDAP password are available for the script.

Finally, I needed to customize the login page and the translations for the login page, that why I created this last role `gluu-customization` to copy files in the directory used by gluu.

For xhtml file: 
- `/opt/gluu-server-{{ gluu_version }}/opt/gluu/jetty/[identity|oxauth]/custom/pages/WEB-INF/incl/layout/login-template.xhtml`
- `/opt/gluu-server-{{ gluu_version }}/opt/gluu/jetty/[identity|oxauth]/custom/pages/login.xhtml`

For the translations, the files can't be updated outside the WAR file, so I added `gluu_customize_wars` to upack, update and repack the WAR file.
Since version 3.0.2, I didn't check if Gluu updated it to allow external files for the translation.



I hope you will find all the information you need. Gluu can be difficult to understand with the container/chroot, configuration files and configuration in the LDAP.
